-- 007: label stream + lot-level features. Source of record for what is live in
-- Supabase (migrations lead_outcomes_label_stream, parcel_lot_features,
-- lot_features_apply_rpc, lot_features_pgnet_loader — all 2026-09-16 22:54–23:00 UTC).
-- Exported from the live schema 2026-09-17; edit here, apply via SQL editor.

-- ---------------------------------------------------------------------------
-- A. lead_outcomes — the calibration label stream (spec §3 "back-fit against
--    closed jobs"). One row per lead once a rep knows the result. The BEFORE
--    INSERT trigger freezes the parcel's model inputs at that moment so later
--    rescoring never rewrites history.
--    lead_outcomes_readiness() says when there is enough to fit weights
--    (>=100 won/lost with parcel, >=30 won; or >=100 water yes/no, >=30 each).
-- ---------------------------------------------------------------------------
create table if not exists public.lead_outcomes (
  id                 bigint generated by default as identity primary key,
  lead_key           text not null,          -- stable key from the CRM lead store
  lead_id            text,
  parcel_id          text,
  address            text,
  city               text,
  zip                text,
  outcome            text not null check (outcome in ('won', 'lost', 'no_show')),
  amount             numeric,
  package            text,
  lost_reason        text,
  water_confirmed    boolean,                -- rep saw water on site (the second label)
  water_where        text[] not null default '{}',
  water_depth_in     real,
  water_last_seen    date,
  assessed_at        date,
  rep                text,
  notes              text,
  -- snapshot of model inputs at insert time
  fsi_live_at        real,
  fsi_static_at      real,
  must_have_score_at real,
  must_have_band_at  text,
  fema_zone_at       text,
  hsg_at             text,
  claim_heat_at      real,
  twi_n_at           real,
  hand_n_at          real,
  rain_24h_at        real,
  api_at             real,
  source             text not null default 'crm',
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create unique index if not exists lead_outcomes_lead_key_uidx on public.lead_outcomes (lead_key);
create index if not exists lead_outcomes_parcel_idx on public.lead_outcomes (parcel_id);
create index if not exists lead_outcomes_created_idx on public.lead_outcomes (created_at desc);
alter table public.lead_outcomes enable row level security;
revoke all on table public.lead_outcomes from anon, authenticated;
grant select, insert, update, delete, truncate, references, trigger on table public.lead_outcomes to service_role;

create or replace function public.touch_updated_at()
returns trigger language plpgsql
as $$ begin new.updated_at := now(); return new; end $$;

create or replace function public.lead_outcomes_snapshot()
returns trigger
language plpgsql security definer
set search_path = public
as $$
declare
  p public.parcel_risk%rowtype;
  rs public.rainfall_state%rowtype;
begin
  new.updated_at := now();
  if new.parcel_id is not null then
    select * into p from public.parcel_risk where parcel_id = new.parcel_id;
    if found then
      new.fsi_live_at        := p.fsi_live;
      new.fsi_static_at      := p.fsi_static;
      new.must_have_score_at := p.must_have_score;
      new.must_have_band_at  := p.must_have_band;
      new.fema_zone_at       := p.fema_zone;
      new.hsg_at             := p.hsg;
      new.claim_heat_at      := p.claim_heat;
      new.twi_n_at           := p.twi_n;
      new.hand_n_at          := p.hand_n;
      if new.address is null then new.address := p.address; end if;
      if new.city is null then new.city := p.city; end if;
      if new.zip is null then new.zip := p.zip; end if;
    end if;
  end if;
  select * into rs from public.rainfall_state where county_fips = '12127';
  if found then
    new.rain_24h_at := rs.rain_24h;
    new.api_at      := rs.api_value;
  end if;
  return new;
end;
$$;

drop trigger if exists lead_outcomes_snapshot_trg on public.lead_outcomes;
create trigger lead_outcomes_snapshot_trg before insert on public.lead_outcomes
  for each row execute function public.lead_outcomes_snapshot();
drop trigger if exists lead_outcomes_touch_trg on public.lead_outcomes;
create trigger lead_outcomes_touch_trg before update on public.lead_outcomes
  for each row execute function public.touch_updated_at();

create or replace function public.lead_outcomes_readiness()
returns table(outcomes bigint, won bigint, lost bigint, no_show bigint, water_assessed bigint,
              water_yes bigint, water_no bigint, with_parcel bigint,
              ready_p_close boolean, ready_p_water boolean)
language sql stable security definer
set search_path = public
as $$
  select
    count(*),
    count(*) filter (where outcome = 'won'),
    count(*) filter (where outcome = 'lost'),
    count(*) filter (where outcome = 'no_show'),
    count(*) filter (where water_confirmed is not null),
    count(*) filter (where water_confirmed),
    count(*) filter (where water_confirmed = false),
    count(*) filter (where parcel_id is not null),
    count(*) filter (where parcel_id is not null and outcome in ('won','lost')) >= 100
      and count(*) filter (where parcel_id is not null and outcome = 'won') >= 30,
    count(*) filter (where parcel_id is not null and water_confirmed is not null) >= 100
      and least(count(*) filter (where parcel_id is not null and water_confirmed),
                count(*) filter (where parcel_id is not null and water_confirmed = false)) >= 30
  from public.lead_outcomes
$$;

-- ---------------------------------------------------------------------------
-- B. Lot-level features on parcel_risk, loaded from the Volusia property
--    appraiser ArcGIS layer through pg_net (no Vercel budget involved).
--    Loaded 2026-09-16: 315 pages × 1000, 312,369 parcels patched, 0 errors.
--    Populated: lot_sqft 238k, footprint 249k, impervious_ratio 189k, stories 227k.
--    NOT yet used by must_have_raw() — that is the next scoring change.
-- ---------------------------------------------------------------------------
alter table public.parcel_risk
  add column if not exists lot_sqft         real,
  add column if not exists stories          real,
  add column if not exists bldg_count       integer,
  add column if not exists living_units     integer,
  add column if not exists com_area         real,
  add column if not exists impr_just        real,
  add column if not exists land_just        real,
  add column if not exists footprint_sqft   real,
  add column if not exists impervious_ratio real,
  add column if not exists lot_features_at  timestamptz;

create table if not exists public.lot_enrich_queue (
  req_id       bigint primary key,           -- net._http_response.id
  page_offset  integer not null,
  queued_at    timestamptz not null default now(),
  processed_at timestamptz,
  n_rows       integer,
  n_patched    integer,
  status_code  integer,
  error        text
);
alter table public.lot_enrich_queue enable row level security;
revoke all on table public.lot_enrich_queue from anon, authenticated;
grant select, insert, update, delete, truncate, references, trigger on table public.lot_enrich_queue to service_role;

create or replace function public.lot_features_from_arcgis(content jsonb)
returns jsonb
language sql immutable
as $$
  with a as (
    select f->'attributes' as x from jsonb_array_elements(content->'features') f
  ), r as (
    select
      nullif(trim(x->>'PARID'), '') as parcel_id,
      coalesce(
        nullif((x->>'LANDSQFT')::double precision, 0),
        nullif((x->>'CALCACRES')::double precision, 0) * 43560,
        nullif((x->>'LANDACRES')::double precision, 0) * 43560) as lot_sqft,
      coalesce(nullif((x->>'RES_MAX_STORIES')::double precision, 0), nullif((x->>'COM_MAX_STORIES')::double precision, 0)) as stories,
      nullif(coalesce((x->>'BLDGCOUNT')::double precision, 0) + coalesce((x->>'COM_BLDGCOUNT')::double precision, 0), 0) as bldg_count,
      nullif((x->>'LIVUNIT')::double precision, 0) as living_units,
      nullif((x->>'COM_TOTALAREA')::double precision, 0) as com_area,
      nullif((x->>'IMPRJUST')::double precision, 0) as impr_just,
      nullif((x->>'LANDJUST')::double precision, 0) as land_just
    from a
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'parcel_id', parcel_id,
    'lot_sqft', case when lot_sqft > 0 then round(lot_sqft) end,
    'stories', case when stories > 0 then round(stories::numeric, 1) end,
    'bldg_count', case when bldg_count > 0 then round(bldg_count) end,
    'living_units', case when living_units > 0 then round(living_units) end,
    'com_area', case when com_area > 0 then com_area end,
    'impr_just', case when impr_just > 0 then impr_just end,
    'land_just', case when land_just > 0 then land_just end)), '[]'::jsonb)
  from r where parcel_id is not null
$$;

create or replace function public.lot_features_apply(rows jsonb)
returns integer
language plpgsql security definer
set search_path = public
as $$
declare n integer;
begin
  update public.parcel_risk p
     set lot_sqft     = v.lot_sqft,
         stories      = v.stories,
         bldg_count   = v.bldg_count,
         living_units = v.living_units,
         com_area     = v.com_area,
         impr_just    = v.impr_just,
         land_just    = v.land_just,
         lot_features_at = now()
    from jsonb_to_recordset(rows) as v(
      parcel_id text, lot_sqft real, stories real, bldg_count int,
      living_units int, com_area real, impr_just real, land_just real)
   where p.parcel_id = v.parcel_id;
  get diagnostics n = row_count;
  return n;
end;
$$;

-- footprint ≈ conditioned area / stories; impervious ≈ footprint / lot.
create or replace function public.lot_features_derive()
returns integer
language plpgsql security definer
set search_path = public
set statement_timeout = '600s'
as $$
declare n integer;
begin
  update public.parcel_risk
     set footprint_sqft = f.footprint,
         impervious_ratio = case
           when f.footprint is not null and lot_sqft > 0
             then least(1.0, f.footprint / lot_sqft)
           else null end
    from (
      select parcel_id,
             case
               when coalesce(living_area, 0) > 0 then living_area / greatest(coalesce(stories, 1), 1)
               when coalesce(com_area, 0) > 0    then com_area   / greatest(coalesce(stories, 1), 1)
               else null end as footprint
        from public.parcel_risk
       where lot_features_at is not null
    ) f
   where f.parcel_id = parcel_risk.parcel_id;
  get diagnostics n = row_count;
  return n;
end;
$$;

-- Queue N pages of the appraiser layer via pg_net, then drain with lot_enrich_process().
--   select lot_enrich_enqueue(0, 320, 1000);   -- ~312k parcels
--   select * from lot_enrich_process(50);      -- repeat until pending = 0
--   select lot_features_derive();
create or replace function public.lot_enrich_enqueue(from_offset integer default 0, pages integer default 320, page_size integer default 1000)
returns integer
language plpgsql security definer
set search_path = public, extensions
as $$
declare i int; rid bigint; url text;
begin
  for i in 0..pages-1 loop
    url := 'https://maps2.vcgov.org/arcgis/rest/services/Pictometry_Parcels/MapServer/0/query'
      || '?where=1%3D1&outFields=OBJECTID,PARID,LANDSQFT,CALCACRES,LANDACRES,RES_MAX_STORIES,COM_MAX_STORIES,BLDGCOUNT,COM_BLDGCOUNT,LIVUNIT,COM_TOTALAREA,IMPRJUST,LANDJUST'
      || '&returnGeometry=false&orderByFields=OBJECTID&f=json'
      || '&resultOffset=' || (from_offset + i * page_size) || '&resultRecordCount=' || page_size;
    rid := net.http_get(url, timeout_milliseconds := 60000);
    insert into public.lot_enrich_queue (req_id, page_offset) values (rid, from_offset + i * page_size);
  end loop;
  return pages;
end;
$$;

create or replace function public.lot_enrich_process(max_pages integer default 50)
returns table(processed integer, patched integer, pending integer, failed integer)
language plpgsql security definer
set search_path = public, extensions
set statement_timeout = '600s'
as $$
declare q record; rows jsonb; n int; c_proc int := 0; c_patch int := 0;
begin
  for q in
    select lq.req_id, lq.page_offset, r.status_code, r.content, r.error_msg, r.timed_out
      from public.lot_enrich_queue lq
      join net._http_response r on r.id = lq.req_id
     where lq.processed_at is null
     order by lq.page_offset
     limit max_pages
  loop
    begin
      if q.status_code = 200 and q.content is not null then
        rows := public.lot_features_from_arcgis(q.content::jsonb);
        n := public.lot_features_apply(rows);
        update public.lot_enrich_queue set processed_at = now(), status_code = q.status_code,
               n_rows = jsonb_array_length(rows), n_patched = n where req_id = q.req_id;
        c_patch := c_patch + n;
      else
        update public.lot_enrich_queue set processed_at = now(), status_code = q.status_code,
               error = coalesce(q.error_msg, 'timeout=' || q.timed_out::text) where req_id = q.req_id;
      end if;
    exception when others then
      update public.lot_enrich_queue set processed_at = now(), error = sqlerrm where req_id = q.req_id;
    end;
    delete from net._http_response where id = q.req_id;
    c_proc := c_proc + 1;
  end loop;
  return query select c_proc, c_patch,
    (select count(*)::int from public.lot_enrich_queue where processed_at is null),
    (select count(*)::int from public.lot_enrich_queue where error is not null);
end;
$$;
